# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569da9cecafc479b61dcf6b78c0d7f6ed159cd7fa1449244e60dfee75f5752516749453a3d411289c2a305f1b40f52348fa5c59ad810a13692db5f172bf28f8c

test:
  secret_key_base: addb29fadec420467d613a19307a0920a4f17ce64f19b322a3c5e6cdc16c133f22afab283c097648e56b6f85748dd39bcae5ccff0ca3137a09d87d27acc29222

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
